server:
  port: 8082

spring:
  application:
    name: fraud-detection-service
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      properties:
        enable.idempotence: true
        compression.type: lz4
        linger.ms: 10

fraud:
  rules:
    max-single-amount: 10000
    max-transactions-per-minute: 20

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always

logging:
  pattern:
    level: "%5p [traceId=%X{traceId:-}]"
